# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PythonScript\MemAnalyzer\QtApp\MemAnalyzer\widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(400, 300)
        self.Button_FileSelect = QtWidgets.QPushButton(Widget)
        self.Button_FileSelect.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.Button_FileSelect.setObjectName("Button_FileSelect")
        self.lineEdit = QtWidgets.QLineEdit(Widget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 10, 281, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.groupBox = QtWidgets.QGroupBox(Widget)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 281, 231))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 60, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(80, 30, 54, 12))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(160, 30, 54, 12))
        self.label_5.setObjectName("label_5")
        self.lineEdit_E1ID = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_E1ID.setGeometry(QtCore.QRect(80, 60, 41, 20))
        self.lineEdit_E1ID.setObjectName("lineEdit_E1ID")
        self.lineEdit_E2ID = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_E2ID.setGeometry(QtCore.QRect(80, 100, 41, 20))
        self.lineEdit_E2ID.setObjectName("lineEdit_E2ID")
        self.lineEdit_FID = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_FID.setGeometry(QtCore.QRect(80, 140, 41, 20))
        self.lineEdit_FID.setObjectName("lineEdit_FID")
        self.lineEdit_E1Size = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_E1Size.setGeometry(QtCore.QRect(160, 60, 41, 20))
        self.lineEdit_E1Size.setObjectName("lineEdit_E1Size")
        self.lineEdit_E2Size = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_E2Size.setGeometry(QtCore.QRect(160, 100, 41, 20))
        self.lineEdit_E2Size.setObjectName("lineEdit_E2Size")
        self.lineEdit_FSize = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_FSize.setGeometry(QtCore.QRect(160, 140, 41, 20))
        self.lineEdit_FSize.setObjectName("lineEdit_FSize")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(210, 60, 54, 12))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(210, 100, 54, 12))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(210, 140, 54, 12))
        self.label_8.setObjectName("label_8")
        self.pushButton0 = QtWidgets.QPushButton(Widget)
        self.pushButton0.setGeometry(QtCore.QRect(310, 60, 75, 23))
        self.pushButton0.setObjectName("pushButton0")
        self.pushButton1 = QtWidgets.QPushButton(Widget)
        self.pushButton1.setGeometry(QtCore.QRect(310, 100, 75, 23))
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton2 = QtWidgets.QPushButton(Widget)
        self.pushButton2.setGeometry(QtCore.QRect(310, 140, 75, 23))
        self.pushButton2.setObjectName("pushButton2")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "MemAnalyzerV1.0"))
        self.Button_FileSelect.setText(_translate("Widget", "SelectFile"))
        self.groupBox.setTitle(_translate("Widget", "Parameters"))
        self.label.setText(_translate("Widget", "EEPROM1"))
        self.label_2.setText(_translate("Widget", "EEPROM2"))
        self.label_3.setText(_translate("Widget", "FLASH"))
        self.label_4.setText(_translate("Widget", "Chip ID"))
        self.label_5.setText(_translate("Widget", "ChipSize"))
        self.label_6.setText(_translate("Widget", "K Bytes"))
        self.label_7.setText(_translate("Widget", "K Bytes"))
        self.label_8.setText(_translate("Widget", "M Bytes"))
        self.pushButton0.setText(_translate("Widget", "EE1Print"))
        self.pushButton1.setText(_translate("Widget", "EE2Print"))
        self.pushButton2.setText(_translate("Widget", "FLSPrint"))
